ALTER TABLE Users
ADD COLUMN FirstName VARCHAR(100) NULL AFTER UserID,
ADD COLUMN Surname VARCHAR(100) NULL AFTER FirstName,
ADD COLUMN DateOfBirth DATE NULL AFTER Surname,
ADD COLUMN Address TEXT NULL AFTER DateOfBirth,
ADD COLUMN PhoneNumber VARCHAR(20) NULL AFTER Address,
ADD COLUMN IDType VARCHAR(50) NULL AFTER PhoneNumber,
ADD COLUMN IDNumber VARCHAR(100) NULL AFTER IDType,
ADD COLUMN IDUpload VARCHAR(255) NULL AFTER IDNumber;
